# Generated by Django 4.0.4 on 2022-05-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unicorn',
            name='color',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unicorn',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unicorn',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
